version: "3.9"

services:

  customer-db:
    image: mysql:8
    container_name: customer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerdb
    ports:
      - "3307:3306"
    restart: always

    volumes:
      - customer-data:/var/lib/mysql

  booking-db:
    image: mysql:8
    container_name: booking-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingdb
    ports:
      - "3309:3306"
    restart: always

    volumes:
      - booking-data:/var/lib/mysql

  customer-service:
    container_name: customer-service
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - customer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://customer-db:3306/customerdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  booking-service:
    container_name: booking-service
    build: ./booking-service
    ports:
      - "8080:8080"
    depends_on:
      - booking-db
      - customer-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://booking-db:3306/bookingdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  customer-data:
  booking-data:
